# .github/workflows/tests.yml
name: Run test Application and run tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      APP_URL: "http://127.0.0.1:8080/"
      API_URL: "http://127.0.0.1:8080/api"
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SYSTEM_PASSWORD: ${{ secrets.SYSTEM_PASSWORD }}

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка системных зависимостей
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libpq-dev postgresql-16 screen

      - name: Настройка БД
        run: |
          sudo pg_ctlcluster 16 main start
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD'"
          sudo -u postgres psql -c "CREATE DATABASE django_rest"

      - name: Установка python зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Старт приложения
        run: |
          python app/manage.py migrate
          screen -d -m python app/manage.py runserver 8080
          sleep 5

      - name: Прогон автотестов
        run: |
          pytest ./tests --html=./reports/report.html

      - name: Сохранение HTML отчёта
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports